# Generated by Django 6.1 on 2026-08-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
